apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snapshot-of-pvol0
  namespace: test
spec:
  volumeSnapshotClassName: isilon-snapclass
  source:
    persistentVolumeClaimName: pvol0
